/**
 * dsh-plugin-background build script.
 *
 * Bundles src/ (TypeScript, multi-file feature chunks) into the single-file
 * module-loader bundle lib/client.js. The harness serves that bundle
 * directly, so it must keep the `window.__ModuleLoader__.load` shape: the
 * banner opens the loader registration and factory, esbuild emits its IIFE
 * inside, and the footer returns module.exports. Platform modules stay
 * external — they resolve through the loader's require() at runtime.
 *
 *   node build.mjs        (bundle)
 *   npx tsc --noEmit      (type-check, optional)
 */
import { build } from "esbuild";

const banner = [
	"/**",
	" * dsh-plugin-background — browser bundle (dshClient ./client).",
	" * GENERATED by build.mjs from src/ (TypeScript). Do not edit directly.",
	" */",
	"window.__ModuleLoader__.load({",
	"\tid: \"dsh-plugin-background\",",
	"\tfactory: (require) => {",
	"\t\tvar module = { exports: {} };",
	"\t\tvar exports = module.exports;",
	"\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: \"Module\" });"
].join("\n");

const footer = [
	"",
	"\t\treturn module.exports;",
	"\t}",
	"});",
	""
].join("\n");

await build({
	entryPoints: ["src/entry.ts"],
	bundle: true,
	outfile: "lib/client.js",
	format: "iife",
	platform: "browser",
	target: "es2020",
	external: [
		"react",
		"react/jsx-runtime",
		"@deepseek-ai/dsh-client-ui-primitives",
		"@deepseek-ai/dsh-client-runtime/client"
	],
	banner: { js: banner },
	footer: { js: footer },
	sourcemap: false,
	minify: false,
	logLevel: "info"
});

console.log("built lib/client.js");
